# -*- coding: utf-8 -*-
"""ejercicio1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RVK9cz44norPCw4O4WyUkjDyxJtxgOrf
"""

#informacion personal
numidentificacion=80880539
print(numidentificacion)
nombre="Anderson"
print(nombre)
apellidos="Benavides Hernandez"
print(apellidos)
dir="calle 57  No 78  25"
print(dir)
celular=3007306911
print(celular)
edad=38
print(edad)
estadocivil="soltero"
print(estadocivil)
Nodehijos=1
print(Nodehijos)
estatura=175
print(estatura)
fechadecontrato=752017
print(fechadecontrato)
sueldobase=2500000
print(sueldobase)
diaslab=1810
print(diaslab)

# empleado con bono 5%
edad= int(input("digite su edad"))
salario=int(input("dijite su salario"))
if edad >= 55
  print("tiene bono del 5% ")
else:
  print("no tiene bono")  
  edad = 56

# casado y numero de hijos
estadocivil = input("su estado")
if stadocivil = casado
Nodehijos= int(input("digite Nodehijos"))
if"estadocivil=casado, Nodehijos›1")
  print("paseo otorgado")
else("no tiene paseo") 
  print("no tiene paseo")

# comision por salario
salario= int(input("escriba su salario"))
if salario ›=1000000 and ‹=1500000
  print("incremento 2%")
else 
print("no tiene incremento")  
salario2= int(input("escriba su salario"))
if salario2 ›1500000 and ‹2000000
  print("incremento 5%")